name = "stonks"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables will be defined here
# For local development, create a .env file with FINNHUB_API_KEY
# For production, set FINNHUB_API_KEY as a secret: wrangler secret put FINNHUB_API_KEY

# Static assets (service worker, manifest, icons)
[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "STONKS_DB"
database_name = "stonks-portfolio"
database_id = "0015b265-8d4e-4e57-9f18-c8973ecb46c6"

routes = [
  "*haydencarson.com/stonks/*"
]